{% set version = '1.6.2' %}
{% set github = 'https://github.com/EDIorg/taxonomyCleanr' %}
{% set commit = '0814cf931e779526f5dff60307a4a6cddc1292d7' %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-taxonomycleanr
  version: {{ version|replace("-", "_") }}

source:
  url: {{ github }}/archive/{{ commit }}.tar.gz
  sha256: 6b83f20a71bc417bec0d214893c4d575cd5f85451cb74d53490cd959fc5972d7

build:
  number: 3
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-data.table >=1.12.2
    - r-stringr >=1.2.0
    - r-taxize >=0.9.99
    - r-ritis >=1.0.0
    - r-covr
    - r-eml >=2.0.3
    - r-httr >=1.4.1
    - r-worrms >=0.4.2
  run:
    - r-base
    - r-data.table >=1.12.2
    - r-stringr >=1.2.0
    - r-taxize >=0.9.99
    - r-ritis >=1.0.0
    - r-covr
    - r-eml >=2.0.3
    - r-httr >=1.4.1
    - r-worrms >=0.4.2

test:
  commands:
    - $R -e "library('taxonomyCleanr')"           # [not win]
    - "\"%R%\" -e \"library('taxonomyCleanr')\""  # [win]

about:
  home: {{ github }}
  license: MIT
  summary: Resolves user supplied taxonomy data against a taxonomic authority, retrieves taxonomic 
    serial numbers, updates users data, and creates the taxonomicCoverage metadata element in 
    the Ecological Metadata Language (EML).
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - marie59

# Package: taxonomyCleanr
# Type: Package
# Title: A workflow and set of functions to clean taxonomy data using R
# Version: 1.6.2
# Date: 
# Author: person("Colin", "Smith", email = "csmith.tar@gmail.com", role = c("aut", "cre"), comment = "https://orcid.org/0000-0003-2261-9931")
# Maintainer: Smith Colin <csmith.tar@gmail.com>
# Description: Resolves user supplied taxonomy data against a taxonomic authority, retrieves taxonomic 
#    serial numbers, updates users data, and creates the taxonomicCoverage metadata element in 
#    the Ecological Metadata Language (EML).
# Depends: R (>= 2.14)
# Suggests: testthat, knitr, rmarkdown
# License: MIT + file LICENSE
# URL: https://github.com/EDIorg/taxonomyCleanr
# BugReports: https://github.com/EDIorg/taxonomyCleanr/issues
# LazyData: true
# RoxygenNote: 7.1.1
# Packaged: 
# NeedsCompilation: yes
# Repository: github
# Date/Publication: 
